# Generated by Django 3.0.2 on 2020-03-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='fulltext',
            field=models.TextField(default='', null=True),
        ),
    ]
